Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceBeforeBrackets: 
  Enabled: true
Lint/AmbiguousAssignment: 
  Enabled: true
Lint/DuplicateBranch: 
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: 
  Enabled: true
Lint/EmptyBlock: 
  Enabled: true
Style/Documentation: 
  Enabled: false
Style/StringLiterals: 
  Enabled: false
Lint/EmptyClass: 
  Enabled: true
Lint/NoReturnInBeginEndBlocks: 
  Enabled: true
Lint/ToEnumArguments: 
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
  Max: 99
Lint/UnexpectedBlockArity: 
  Enabled: true
AllCops:
    SuggestExtensions: false
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding: 
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition: 
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/NegatedIfElseCondition: 
  Enabled: true
Style/NilLambda: 
  Enabled: true
Style/RedundantArgument: 
  Enabled: true
Style/SwapValues: 
  Enabled: true